### ISSUE TITLE
Having a checklist tool for release

### ISSUE THREAD

**Issue by juherr** [cbeust/testng#1628]
Before each release, we have to do some manual checks.
A script could be used in order to check if a release is valid.

Related issues: #1627 

Check list:
- [ ] Version in the version file
- [ ] Javadoc jar not empty
- [ ] Sources jar not empty
- [ ] Provided/optional dependencies
- [ ] Dependencies available on maven central
- [ ] Java major version used (java 7 => 52)
- [ ] MANIFEST position (#1640)
- [ ] OSGI Headers (#1678)
- [ ] Git tag

**Comment by juherr** [comment]
https://blog.jooq.org/2017/11/28/how-to-ensure-your-code-works-with-older-jdks/
https://github.com/xvik/gradle-animalsniffer-plugin

**Comment by juherr** [comment]
Duplicate of #1492
